// @ts-check
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import tseslint from 'typescript-eslint';
import prettierConfig from 'eslint-config-prettier';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Import boundaries
//
// This is the mechanical enforcement of the import matrix in
// docs/architecture/source-structure.md. Without it the matrix is a document
// people mean to follow; with it, a violation fails the build.
//
// The rule that matters most: lib/core must stay pure. It holds every money
// calculation, and its purity is what makes exhaustive unit testing cheap and
// What-If (spec §18) possible without new math. A single `import { useState }`
// or `Date.now()` in there quietly undoes both.
// ---------------------------------------------------------------------------

/** Packages lib/core may never touch. Each ban has a reason. */
const CORE_FORBIDDEN_PACKAGES = [
  {
    group: ['react', 'react/*', 'react-dom', 'react-dom/*'],
    message:
      'lib/core is pure domain logic and must not import React. Move UI concerns to components/.',
  },
  {
    group: ['next', 'next/*'],
    message:
      'lib/core must not import Next. It must not know it is running in a web app.',
  },
  {
    group: ['@supabase/*'],
    message:
      'lib/core must not perform I/O. Fetch in lib/server and pass plain data in.',
  },
  {
    group: ['zod', 'zod/*'],
    message:
      'Validation belongs at the boundary (lib/validation). lib/core receives already-valid input.',
  },
  {
    group: ['date-fns', 'date-fns/*', 'dayjs', 'dayjs/*', 'luxon', 'moment'],
    message:
      "No date libraries in lib/core. Recurrence math runs on calendar dates in the user's timezone, never UTC instants — a library API invites exactly that bug. See docs/domain/recurrence.md.",
  },
  {
    group: ['recharts', 'recharts/*', 'd3', 'd3-*'],
    message: 'Charting belongs in components/charts only.',
  },
];

/** Only components/charts may import the charting library. */
const CHART_PACKAGES = {
  group: ['recharts', 'recharts/*', 'd3', 'd3-*'],
  message:
    'Import charts only inside components/charts, so the library stays swappable and out of other bundles. See docs/architecture/frontend-architecture.md#chart-isolation.',
};

/** The service_role client bypasses ALL row level security. */
const ADMIN_CLIENT = {
  group: ['**/lib/server/supabase/admin', '@/lib/server/supabase/admin'],
  message:
    'The admin client bypasses row level security. It is allowed only in migration tooling and seed scripts — never in anything reachable from app/. If a feature seems to need it, the RLS policy is wrong. See docs/security/security-model.md.',
};

const SERVER_ONLY = {
  group: [
    '**/lib/server',
    '**/lib/server/**',
    '@/lib/server',
    '@/lib/server/**',
  ],
  message:
    'Components must not import lib/server. Data is fetched in a Server Component and passed down as props.',
};

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'next-env.d.ts',
      // Generated by `supabase gen types` — never hand-edited, so never linted.
      'types/database.types.ts',
      // Deliberate violations. Linted explicitly by `npm run lint:boundaries`
      // to prove the rules still bite; excluded here so they do not fail the
      // ordinary lint run.
      'tests/fixtures/lint/**',
    ],
  },

  // Next.js + React rules. eslint-config-next 16 ships a native flat config,
  // so this needs no FlatCompat shim.
  ...nextCoreWebVitals,

  // Type-aware TypeScript rules.
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
  },

  // -------------------------------------------------------------------------
  // Matrix row 1 — lib/core: may import lib/core and the stdlib. Nothing else.
  // -------------------------------------------------------------------------
  {
    files: ['lib/core/**/*.ts', '**/lint/lib/core/**/*.ts'],
    rules: {
      'no-restricted-imports': ['error', { patterns: CORE_FORBIDDEN_PACKAGES }],
      // `today` is always injected so month-boundary and leap-year cases are
      // ordinary test inputs rather than something needing a fake clock.
      'no-restricted-globals': [
        'error',
        {
          name: 'Date',
          message:
            'lib/core must not read the clock. Inject `today` as a parameter. See docs/adr/0003-pure-typescript-domain-core.md.',
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'Date',
          property: 'now',
          message: 'lib/core must not read the clock. Inject `today`.',
        },
        {
          object: 'process',
          property: 'env',
          message:
            'A pure function must depend only on its arguments. Pass configuration in.',
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'NewExpression[callee.name="Date"]',
          message:
            'lib/core must not construct dates from the clock. Inject `today` as a CalendarDate.',
        },
        {
          selector:
            "MemberExpression[object.name='process'][property.name='env']",
          message: 'lib/core must not read process.env.',
        },
      ],
    },
  },

  // -------------------------------------------------------------------------
  // Matrix rows 2-4 — lib/server, lib/validation, lib/utils
  // -------------------------------------------------------------------------
  {
    files: [
      'lib/server/**/*.ts',
      'lib/server/**/*.tsx',
      '**/lint/lib/server/**/*.{ts,tsx}',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/components/**', '@/components/**'],
              message:
                'lib/server must not import components. Data flows server -> component, never back.',
            },
            CHART_PACKAGES,
          ],
        },
      ],
    },
  },
  {
    files: ['lib/validation/**/*.ts', '**/lint/lib/validation/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            SERVER_ONLY,
            {
              group: ['**/components/**', '@/components/**'],
              message:
                'lib/validation is shared by server actions and client forms. It must not depend on either.',
            },
            CHART_PACKAGES,
          ],
        },
      ],
    },
  },
  {
    files: ['lib/utils/**/*.ts', '**/lint/lib/utils/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            SERVER_ONLY,
            {
              group: ['react', 'react/*', 'react-dom', 'react-dom/*'],
              message: 'lib/utils is framework-agnostic. Keep React out of it.',
            },
            CHART_PACKAGES,
          ],
        },
      ],
    },
  },

  // -------------------------------------------------------------------------
  // Matrix row 5 — app/**: everything except the admin client.
  // -------------------------------------------------------------------------
  {
    files: ['app/**/*.ts', 'app/**/*.tsx', '**/lint/app/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: [ADMIN_CLIENT, CHART_PACKAGES] },
      ],
    },
  },

  // -------------------------------------------------------------------------
  // Matrix rows 6-8 — components/**: no lib/server, no supabase-js, and the
  // charting library only inside components/charts.
  // -------------------------------------------------------------------------
  {
    files: [
      'components/**/*.ts',
      'components/**/*.tsx',
      '**/lint/components/**/*.{ts,tsx}',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            SERVER_ONLY,
            ADMIN_CLIENT,
            {
              group: ['@supabase/*'],
              message:
                'Components must not talk to the database. Fetch in a Server Component and pass data down.',
            },
            CHART_PACKAGES,
          ],
        },
      ],
    },
  },
  {
    // The one place the charting library is allowed.
    files: [
      'components/charts/**/*.ts',
      'components/charts/**/*.tsx',
      '**/lint/components/charts/**/*.{ts,tsx}',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: [SERVER_ONLY, ADMIN_CLIENT] },
      ],
    },
  },

  // -------------------------------------------------------------------------
  // The admin client's own allowlist: migration tooling and seed scripts.
  // -------------------------------------------------------------------------
  {
    files: ['scripts/**/*.ts', 'supabase/**/*.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },

  // Tests assert on internals and use fixtures freely.
  {
    files: ['tests/**/*.ts', 'tests/**/*.tsx', '**/*.test.ts', '**/*.test.tsx'],
    ignores: ['tests/fixtures/lint/**'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-magic-numbers': 'off',
    },
  },

  // The lint fixtures import modules that do not exist yet, so they are kept
  // out of the main TypeScript program (tsconfig `exclude`). typescript-eslint
  // then cannot type-check them and emits a parser error INSTEAD of the
  // boundary errors — which silently disables the whole check.
  //
  // The import-boundary rules are syntactic and need no type information, so
  // turning off type-aware linting here keeps them firing.
  // `npm run lint:boundaries` proves it: it asserts the specific rule id, so a
  // parser error is not mistaken for enforcement.
  {
    files: ['tests/fixtures/lint/**/*.{ts,tsx}'],
    ...tseslint.configs.disableTypeChecked,
  },

  // Plain Node scripts and config files are not part of the TypeScript
  // program, so type-aware rules cannot run on them.
  {
    files: ['**/*.{js,mjs,cjs}'],
    ...tseslint.configs.disableTypeChecked,
  },

  // Next's config API requires `headers()` / `redirects()` / `rewrites()` to be
  // async even when they return a literal, so require-await is wrong here.
  {
    files: ['next.config.ts'],
    rules: { '@typescript-eslint/require-await': 'off' },
  },

  // Must stay last: turns off every rule Prettier owns.
  prettierConfig,
);
