import { defineConfig } from 'vitest/config';
import { fileURLToPath } from 'node:url';

export default defineConfig({
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('.', import.meta.url)),
    },
  },
  test: {
    // Two projects, because the two suites have genuinely different needs.
    //
    //   unit         pure functions, no I/O, fast enough to run on every save.
    //                This is the primary feedback loop for lib/core.
    //   integration  hits a local Supabase, so it needs a longer timeout and
    //                is kept out of the watch loop.
    //
    // Splitting them means `npm run test` stays fast. A unit suite that waits
    // on a database is a unit suite nobody runs.
    projects: [
      {
        extends: true,
        test: {
          name: 'unit',
          environment: 'node',
          include: ['tests/unit/**/*.test.ts'],
        },
      },
      {
        extends: true,
        test: {
          name: 'integration',
          environment: 'node',
          include: ['tests/integration/**/*.test.ts'],
          // A local Supabase round trip is slower than a pure function call.
          testTimeout: 30_000,
          hookTimeout: 60_000,
          // Integration tests share one database, so running files in parallel
          // means two suites mutating the same rows.
          fileParallelism: false,
          setupFiles: ['tests/integration/setup.ts'],
        },
      },
    ],

    coverage: {
      provider: 'v8',
      // text for a terminal, lcov for CI upload, json-summary so a script can
      // read the numbers without parsing a report.
      reporter: ['text', 'lcov', 'json-summary'],
      reportsDirectory: './coverage',

      // `include` reports on every matching source file, not only files a test
      // happened to import — otherwise an untested module disappears from the
      // report and the global threshold passes while real code is uncovered.
      // (Vitest 5 removed the separate `all` flag; `include` now implies it.)
      include: ['lib/**/*.ts', 'app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}'],

      exclude: [
        'node_modules/**',
        '.next/**',
        'coverage/**',
        'tests/**',
        'scripts/**',
        '**/*.config.{ts,mts,mjs,js}',
        '**/*.d.ts',
        // Generated by `supabase gen types` — never hand-written, so never
        // meaningfully covered.
        'types/database.types.ts',
        // Deliberate lint violations; they are never executed.
        'tests/fixtures/lint/**',
      ],

      thresholds: {
        // Global floor. UI coverage has diminishing returns, so this is
        // deliberately modest — it exists to catch whole untested areas.
        statements: 60,
        branches: 60,
        functions: 60,
        lines: 60,

        // lib/core is the money math. A wrong number there is worse than a
        // crash because it looks like an answer, and the code is pure, so
        // exhaustive testing is cheap. See ADR-0003.
        //
        // safe-to-spend and timeline rise to 95% when they land (M7-B01,
        // M8-B02) — they are the two named differentiators.
        'lib/core/**/*.ts': {
          statements: 90,
          branches: 90,
          functions: 90,
          lines: 90,
        },
      },
    },
  },
});
